### ISSUE TITLE
Error after updating to 1.2.0

### ISSUE THREAD

**Issue by jfloff** [grosser/test_after_commit#51]
I just updated to v1.2.0 and I'm getting this error when I seed the database:
```
NoMethodError: undefined method `records' for #<ActiveRecord::ConnectionAdapters::NullTransaction:0x000000000a51c048>
/app/heroku/ruby/bundle/ruby/2.4.4/gems/test_after_commit-1.2.0/lib/test_after_commit/database_statements.rb:45:in `test_commit_records'
/app/heroku/ruby/bundle/ruby/2.4.4/gems/test_after_commit-1.2.0/lib/test_after_commit/database_statements.rb:29:in `transaction'
```

Any hints on why this is happening?

**Comment by pmavinkurve-mdsol** [comment]
Thanks for reporting this! We are seeing this error too.

**Comment by andreynering** [comment]
Same for us. Maybe an incompatibility with Rails 4.2?

**Comment by taryneast** [comment]
yup, same here... also on Rails 4.2

**Comment by jfloff** [comment]
Can also confirm that I'm on Rails 4.2

**Comment by guizmaii** [comment]
Same here !

**Comment by grosser** [comment]
yanked 1.2.0
plz someone dig deeper and make a PR to fix, cause is most likely https://github.com/grosser/test_after_commit/pull/50 
... ideally also add a new test-case that fails with the current version :D

... if there is no fix I can also release it with a `rails ~> 5.0` requirement
/cc @printercu

**Comment by printercu** [comment]
Can you please provide exact rails version? I've added test-case with `transaction(requires_new: true)` and still can not get an error.

**Comment by grosser** [comment]
v1.2.1.

**Comment by guizmaii** [comment]
Seems to work ! Thanks :)

**Comment by texpert** [comment]
@grosser, in 1.2.1 I got still the same error at line 46 in `transaction.instance_variable_set(:@records...`

Maybe it will be more reliable to check if `original.respond_to?(:records)` ?

**Comment by printercu** [comment]
Can you please provide the error? Here is failing spec with your suggested changes: https://travis-ci.org/grosser/test_after_commit/builds/454615291

**Comment by texpert** [comment]
@printercu , the error is the same:

```
Failure/Error: DatabaseCleaner.start
     
     NoMethodError:
       undefined method `records' for #<ActiveRecord::ConnectionAdapters::NullTransaction:0x007ffa1d26d6e8>
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/test_after_commit-1.2.1/lib/test_after_commit/database_statements.rb:46:in `test_commit_records'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/test_after_commit-1.2.1/lib/test_after_commit/database_statements.rb:30:in `transaction'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/database_cleaner-1.5.1/lib/database_cleaner/active_record/transaction.rb:12:in `start'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/database_cleaner-1.5.1/lib/database_cleaner/base.rb:82:in `start'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:75:in `block in start'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:75:in `each'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:75:in `start'
     # ./spec/support/database_cleaner.rb:14:in `block (2 levels) in <top (required)>'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/ruby-debug-ide-0.7.0.beta4/lib/ruby-debug-ide.rb:99:in `debug_load'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/ruby-debug-ide-0.7.0.beta4/lib/ruby-debug-ide.rb:99:in `debug_program'

1 example, 1 failure, 0 passed
```

**Comment by texpert** [comment]
That's it, @printercu , I wasn't right to remove the 'skip emulation' procedure. The `respond_to?(:records)` should be an additional check.

https://github.com/grosser/test_after_commit/pull/53

**Comment by grosser** [comment]
needs to be an additional check or the only check ?

**Comment by grosser** [comment]
1.2.2
